---
title: "HW 2"
author: "Adon Rosen"
date: "9/29/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the library(s)

```{r load library}
library(foreign) ## Will be used to load .sav file
library(ggplot2) ## Will be used for plotting
library(grid) ## More plotting functions
library(knitr) ## For cosmetics
print("Done loading librarys")
```

## Declare some knitr stuff
```{r knitr mods}
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
```
## Declare a function we will use later
```{r functions}
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}
```

## Answer Question 1 here
### Question 1.A
```{r answer 1a here, echo=FALSE,tidy=TRUE, tidy.opts=list(width.cutoff=60), linewidth=60}
point.estimate <- 25
stand.dev <- 6
n <- 36
print(paste("We are told in the problem that the mean of the sample of OU undergrads is ", point.estimate))
print(paste("We will use this value as our point estimate of mean depression"))
```

### Question 1.B
```{r Obtain the margin of error here, echo=FALSE,tidy=TRUE, tidy.opts=list(width.cutoff=60), linewidth=60}
conf.interval <- qt(c(.975), df=35) 
marg.of.error <- conf.interval * (stand.dev/ sqrt(n))
print(paste("The margin of error is:", marg.of.error))
```

### Question 1.C
```{r Obtain the 95% confidence interval, echo=FALSE,tidy=TRUE, linewidth=60}
upper.limit <- round(point.estimate + marg.of.error, 2)
lower.limit <- round(point.estimate - marg.of.error, 2)
print(paste("The 95% confidence interval for mean OU undergrad depression is: [",lower.limit,",", upper.limit, "]", sep=''))
```

### Question 1.D
```{r Describe the meaning of the confidence interval, echo=FALSE,tidy=TRUE, linewidth=60}
print(paste("The 95% confidence interval of the mean OU undergrad depression rating reflects the variation of mean values we would obtain if the sampiling procedure was repated a large number of times."))
print(paste("Explicitly, we would expect 95% of the means to fall within ", lower.limit, " and ", upper.limit, " from this resampling procedure", sep=''))
```

### Question 1.E
```{r Describe what this means, echo=FALSE,tidy=TRUE, tidy.opts=list(width.cutoff=30), linewidth=60}
print(paste("Given the fact that the national undergraduate mean depression is estimated at 40, and the upper limit of the OU undergraduate mean depression confidence interval was", upper.limit, "we can confidentley state that these two populations exhibit different means"))
```

## Answer question 2 here
```{r Interpreting p-values, echo=FALSE,tidy=TRUE, tidy.opts=list(width.cutoff=60), linewidth=60}
print(paste("A p-value reflects the probability of observing an effect of equal or greater absolute magnitude given a true null hypothesis."))
```

## Answer question 3 here
```{r Declare some statics used for plotting, echo=FALSE}
m1 <- 0  # mu H0
sd1 <- 1.5 # sigma H0
m2 <- 3.5 # mu HA
sd2 <- 1.5 # sigma HA

z_crit <- qnorm(1-(0.05/2), m1, sd1)

# set length of tails
min1 <- m1-sd1*4
max1 <- m1+sd1*4
min2 <- m2-sd2*4
max2 <- m2+sd2*4          
# create x sequence
x <- seq(min(min1,min2), max(max1, max2), .01)
# generate normal dist #1
y1 <- dnorm(x, m1, sd1)
# put in data frame
df1 <- data.frame("x" = x, "y" = y1)
# generate normal dist #2
y2 <- dnorm(x, m2, sd2)
# put in data frame
df2 <- data.frame("x" = x, "y" = y2)

# Alpha polygon
y.poly <- pmin(y1,y2)
poly1 <- data.frame(x=x, y=y.poly)
poly1 <- poly1[poly1$x >= z_crit, ] 
poly1<-rbind(poly1, c(z_crit, 0))  # add lower-left corner

# Beta polygon
poly2 <- df2
poly2 <- poly2[poly2$x <= z_crit,] 
poly2<-rbind(poly2, c(z_crit, 0))  # add lower-left corner

# power polygon; 1-beta
poly3 <- df2
poly3 <- poly3[poly3$x >= z_crit,] 
poly3 <-rbind(poly3, c(z_crit, 0))  # add lower-left corner

# combine polygons. 
poly1$id <- 3 # alpha, give it the highest number to make it the top layer
poly2$id <- 2 # beta
poly3$id <- 1 # power; 1 - beta
poly <- rbind(poly1, poly2, poly3)
poly$id <- factor(poly$id,  labels=c("power","beta","alpha"))
```

```{r Now create the plots displaying alpha, beta, and power, echo = FALSE}
ggplot(poly, aes(x,y, fill=id, group=id)) +
  geom_polygon(show_guide=F, alpha=I(8/10)) +
  # add line for treatment group
  geom_line(data=df1, aes(x,y, color="H0", group=NULL, fill=NULL), size=1.5, show_guide=F) + 
  # add line for treatment group. These lines could be combined into one dataframe.
  geom_line(data=df2, aes(color="HA", group=NULL, fill=NULL),size=1.5, show_guide=F) +
  # add vlines for z_crit
  geom_vline(xintercept = z_crit, size=1, linetype="dashed") +
  # change colors 
  scale_color_manual("Group", 
                     values= c("HA" = "#981e0b","H0" = "black")) +
  scale_fill_manual("test", values= c("alpha" = "#0d6374","beta" = "#be805e","power"="#7cecee")) +
  # beta arrow
  annotate("segment", x=0.1, y=0.045, xend=1.3, yend=0.01, arrow = arrow(length = unit(0.3, "cm")), size=1) +
  annotate("text", label="beta", x=0, y=0.05, parse=T, size=8) +
  # alpha arrow
  annotate("segment", x=4, y=0.043, xend=3.4, yend=0.01, arrow = arrow(length = unit(0.3, "cm")), size=1) +
  annotate("text", label="frac(alpha,2)", x=4.2, y=0.05, parse=T, size=8) +
  # power arrow
  annotate("segment", x=6, y=0.2, xend=4.5, yend=0.15, arrow = arrow(length = unit(0.3, "cm")), size=1) +
  annotate("text", label=expression(paste(1-beta, "  (\"power\")")), x=6.1, y=0.21, parse=T, size=8) +
  # H_0 title
  annotate("text", label="H[0]", x=m1, y=0.28, parse=T, size=8) +
  # H_a title
  annotate("text", label="H[a]", x=m2, y=0.28, parse=T, size=8) +
  ggtitle("Statistical Power Plots") +
  # remove some elements
  theme(panel.grid.minor = element_blank(),
             panel.grid.major = element_blank(),
             panel.background = element_blank(),
             plot.background = element_rect(fill="#f9f0ea"),
             panel.border = element_blank(),
             axis.line = element_blank(),
             axis.text.x = element_blank(),
             axis.text.y = element_blank(),
             axis.ticks = element_blank(),
             axis.title.x = element_blank(),
             axis.title.y = element_blank(),
             plot.title = element_text(size=22))

```

### Answer question 4 here
```{r Answer what contributes to statistical power here, echo=FALSE, linewidth=60}
print(paste("Statistical power is influenced by:"))
print(paste("1. Sample size"))
print(paste("2. Estimated effect sizes"))
print(paste("3. One vs Two directional tests"))
```

### Answer question 5 here
```{r First load the data}
## First load the data
in.data <- read.csv("../HW1/salary.csv")
```
## Question 5.A
```{r Create a histogram of salary by gender}
ggplot(in.data) +
  geom_histogram(data=in.data[which(in.data$gender=="M"),],aes(x=salary), color='blue', alpha=.75, fill='blue') +
  geom_histogram(data=in.data[which(in.data$gender=="F"),],aes(x=salary), color="red", alpha=.75, fill='red')
```

### Question 5.B
```{r Create boxplots of these data}
ggplot(in.data, aes(x=gender, y=salary)) +
  geom_boxplot()
```

### Question 5.C
```{r Plot the mean of gender salary}
plot.data <- summarySE(data=in.data, measurevar = 'salary', groupvars = 'gender')
ggplot(plot.data, aes(x=gender, y=salary, fill=gender)) +
    geom_bar(position=position_dodge(), stat="identity") +
    geom_errorbar(aes(ymin=salary-se, ymax=salary+se),
                  width=.2,                    
                  position=position_dodge(.9)) +
    coord_cartesian(ylim=c(55000, 80000))
```